pluginManagement {
    def glowGradleProps = new Properties()
    def propsFile = new File(settingsDir, 'gradle.properties')
    if (propsFile.exists()) {
        propsFile.withInputStream { glowGradleProps.load(it) }
    }

    repositories {
        def glowMavenUrl = glowGradleProps.getProperty('glowGradlePluginMavenUrl')
        if (glowMavenUrl) {
            maven {
                name = 'GlowGradlePlugin'
                url = uri(glowMavenUrl)
                credentials {
                    if (System.getenv('CI')) {
                        username = 'gitlab-ci-token'
                        password = System.getenv('CI_JOB_TOKEN') ?: ''
                    } else {
                        username = System.getenv('GLOW_GITLAB_USER') ?: ''
                        password = System.getenv('GLOW_GITLAB_TOKEN') ?: ''
                    }
                }
            }
        }
        mavenCentral()
        gradlePluginPortal()
        mavenLocal()
    }
    plugins {
        id glowGradleProps.getProperty('quarkusPluginId') version glowGradleProps.getProperty('quarkusPluginVersion')
        id 'com.glow.local-env' version (glowGradleProps.getProperty('glowGradlePluginVersion') ?: '1.0.0')
    }
}
rootProject.name = 'glow-user-service'
