# HTTP
quarkus.http.port=8080

# OIDC / Keycloak – set up for development purposes
quarkus.oidc.auth-server-url=http://localhost:8080/realms/glow-realm
    # It has been agreed, that Keycloak will run on localhost:8080, so change this if needed
quarkus.oidc.client-id=glow-user-service
quarkus.oidc.credentials.secret=<your-client-secret>
    # The client secret can be found in the Keycloak admin console under:
    # glow-realm > Clients > glow-user-service > Credentials -> Client Secret
quarkus.oidc.tls.verification=none 
    # Deprecated, but since dev localhost is http, this is needed to avoid warnings about insecure connections. Change this to 'required' when using HTTPS in production.

# Datasource – PostgreSQL (H2 temporarily until glow-devops is updated)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=glow
quarkus.datasource.password=glow

# Hibernate
# quarkus.hibernate-orm.database.generation=validate
    # Commented out for now, as it is set up to use a local PostgreSQL instance.
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=true

# Liquibase
quarkus.liquibase.migrate-at-start=false 
    # Liquibase is currently disabled, as it is not yet set up for the user service. 
    # Once it is set up, change this to true to enable automatic migration at startup.

# Kafka – disabled for now, until glow-devops is updated
# mp.messaging.incoming.words-in.auto.offset.reset=earliest
# mp.messaging.incoming.words-in.topic=words
# mp.messaging.outgoing.words-out.topic=words
