quarkus.log.console.json.enabled=false
    # quarkus.log.console.json=false is apparently deprecated

%dev.quarkus.hibernate-orm.enabled=false
    # Hibernate is currently disabled, as it is not yet set up for the user service and it is throwing a warning. Once it is set up, change this to true to enable Hibernate in development mode.